/*
 * This Java source file was generated by the Gradle 'init' task.
 */
package ushallnotpass_public;

import org.junit.Test;
import ushallnotpass_public.encryption.Encryption;

import javax.crypto.BadPaddingException;
import javax.crypto.IllegalBlockSizeException;
import javax.crypto.NoSuchPaddingException;
import javax.crypto.SecretKey;
import javax.crypto.spec.IvParameterSpec;
import java.security.InvalidAlgorithmParameterException;
import java.security.InvalidKeyException;
import java.security.NoSuchAlgorithmException;
import java.security.spec.InvalidKeySpecException;

import static org.hamcrest.CoreMatchers.is;
import static org.hamcrest.MatcherAssert.assertThat;

public class EncryptionTest {

    @Test
    public void decryptedCiphertextShouldEqualInput()
            throws NoSuchAlgorithmException, IllegalBlockSizeException, InvalidKeyException,
            BadPaddingException, InvalidAlgorithmParameterException, NoSuchPaddingException, InvalidKeySpecException {

        String input = "textShouldBeTheSameForInputAndPlaintext12345";
        SecretKey key = Encryption.createSecretKey("mypassword1234", "fixedSalt");
        IvParameterSpec ivParameterSpec = Encryption.generateIv();
        String cipherText = Encryption.encrypt(input, key, ivParameterSpec);

        String plainText = Encryption.decrypt(cipherText, key);
        System.out.println(input);
        System.out.println(cipherText);
        System.out.println(plainText);
        assertThat(input,is(plainText));

    }

}
